project_name: jwt
before:
  hooks:
    - go mod tidy
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
